### ISSUE TITLE
n_g_emissions and n_d_emissions parameters

### ISSUE THREAD

**Issue by milliemince** [fmorenopino/HeterogeneousHMM#2]
Hello - want to use a heterogeneous HMM for a project I'm working on and have a question about the parameters. Say my feature space has 8 Gaussian features and 4 discrete features. I'm assuming then that n_g_emissions = 8 and n_d_emissions = 4... but I'm wondering how the model can tell which features are the Gaussian ones and which are the discrete ones. Is it as simple as putting the Gaussian features before the discrete ones in the input feature matrix? Or does your code somehow recognize which features are Gaussian and which are discrete?

Any clarification on this would be highly appreciated. Thank you!

**Comment by semese** [comment]
Hi,

In order for the model to deal with this you have to arrange your features in the feature matrix such that the first n_g_emissions columns are the Gaussian features, and the last n_d_emissions columns are the discrete features. 

I hope this helped. Do not hesitate to contact us if you encounter further problems.
