### ISSUE TITLE
vectorized version 

### ISSUE THREAD

**Issue by nicolasviboo** [fmorenopino/HeterogeneousHMM#7]
Hi guys, 

I think that your library is super useful. Especially being able to combine continuous and discrete features. It is however not vectorized with respect to the number of samples. Do you plan to have a vectorized version ?

Best, 
Nicolas

**Comment by semese** [comment]
Hi Nicolas, 

Thanks for your message :) 

As you might have noticed, we haven't been working on the library anymore, as it was just a side project for us for our research at the time. But if you'd be interested in collaborating and improving the code in any way, we'd be more than grateful.
